# Generated by Django 3.0.7 on 2020-10-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrestaurants',
            name='R_mobileno',
            field=models.CharField(max_length=20),
        ),
    ]
