# Generated by Django 3.0.7 on 2020-10-16 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_addmenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmenu',
            name='R_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.addRestaurants'),
        ),
    ]
