# Generated by Django 3.0.7 on 2020-10-16 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20201016_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addmenu',
            name='R_name',
        ),
        migrations.AddField(
            model_name='addmenu',
            name='R_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.addRestaurants'),
        ),
    ]
