# Generated by Django 3.0.7 on 2020-10-16 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20201016_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addmenu',
            name='R_id',
        ),
        migrations.AddField(
            model_name='addmenu',
            name='Restaurants',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.addRestaurants'),
        ),
    ]
