# Generated by Django 3.0.7 on 2020-10-19 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20201016_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addmenu',
            old_name='Restaurants',
            new_name='Restaurant',
        ),
    ]
