# Generated by Django 3.0.7 on 2020-10-19 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20201019_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmenu',
            name='Restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.addRestaurants'),
        ),
    ]
